### ISSUE TITLE
Bug with capsule rotation

### ISSUE THREAD

**Issue by temoon** [mhousse1247/UE4-CustomGravityPlugin#2]
Hi! I have a probably bug, but can't fix it by myself. When I tried to change global gravity direction to current forward vector (for example of gizmo root component) Capsule had an incorrect rotation. Another one here is the gizmo root component didn't update self rotation. If use "Is Instant" orientation setting everything is OK. So looks like is something at line 302 of CustomMovementComponent.cpp:
`FMath::RInterpTo(CurrentCapsuleRotation, TargetQuat.Rotator(), DeltaTime, RotationSpeed)`

There is a blueprint to reproduce:
![Blueprint](http://savepic.ru/14980721.jpg)

Settings of my custom pawn:
![1](http://savepic.ru/14948977.jpg)
![2](http://savepic.ru/14986864.jpg)
![3](http://savepic.ru/14978672.jpg)

There is video (red is Capsule rotation, green is Gizmo, before an a bit after the change of global gravity direction): https://youtu.be/43zij9wORjA

**Comment by HoussineMehnik** [comment]
Hi,

Yeah it's an interpolation issue in some cases "RInterpTo"(Rotator) work better , but in your case "Slerp" (Quaternion) will do the trick , all what you have to do is updating that line to this :

`CurrentCapsuleRotation = bInstantRot ? TargetQuat.Rotator() : FQuat::Slerp(CurrentCapsuleRotation.Quaternion(), TargetQuat, DeltaTime* RotationSpeed).Rotator();`


[ue4resources.com/](url)

**Comment by temoon** [comment]
Yes, now it works! Thank you.

**Comment by HoussineMehnik** [comment]
Great!

**Comment by temoon** [comment]
There is not only mine bug — this video illustrates it on your github's "default" project: https://youtu.be/7h3gWFcsQz0 (and there is with fix: https://youtu.be/1mMxAvNnTnI).

You, probably, have to fix it in plugin's code on github.

**Comment by HoussineMehnik** [comment]
Yeah, I know , I don't remember exactly but slerp is causing some wierd issues in some situations too !
I think I will expose an option (bool or enum) to switch between linear / spherical interpolation
